name: code_generation_practice
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  annotations:
    path: annotations/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner:
  generators:
    path: generators/
  source_gen: ^1.5.0
