name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  annotations:
    path: ../annotations/

dev_dependencies:
  build_test:
  build_runner: ^2.4.7
  test: ^1.24.0
